[project]
name = "slack-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.14",
    "fastapi>=0.136.3",
    "langchain-openai>=1.2.2",
    "psycopg[binary,pool]>=3.3.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "slack-bolt>=1.28.0",
    "slack-sdk>=3.42.0",
]
